### ISSUE TITLE
Pybullet can get 96% SR in task of grasping 2 blocks

### ISSUE THREAD

**Issue by pointW** [ColinKohler/helping_hands_rl_envs#7]
In fast mode and 2 block domain, in 305 over 317 episodes the agent gets +1 reward (2 blocks are picked up in 2 steps)

**Comment by ondrejba** [comment]
with a deep Q-network?

**Comment by pointW** [comment]
@ondrejba No, it's just the testing of the simulator itself :P

**Comment by ondrejba** [comment]
ok, I'm getting ahead of myself :D
